### ISSUE TITLE
Finding teammates

### ISSUE THREAD

**Issue by ernbilen** [ernbilen/Data400_Fall24#30]
Hi everyone,
If you are still looking for a teammate for your big project, you can go ahead and respond here with your interests. We can use this channel to start discussions about potential overlaps you may have with others who are also looking for a teammate.
As a reminder, the link to group submissions spreadsheet is [here](https://docs.google.com/spreadsheets/d/1orfYlmn9kpvr2IlXMD8Vxsa43ZDH2e3pedKitFF_I-Q/edit?usp=sharing).

**Comment by HeidiBeardsley** [comment]
Hey everyone! I'm still looking for a partner—my mini project has to do with climate change but I'm also interested in other topics!

**Comment by ccgurek** [comment]
> Hey everyone! I'm still looking for a partner—my mini project has to do with climate change but I'm also interested in other topics!

I'll join you Heidi!
